name: Benchmark

on:
  workflow_dispatch:

env:
  RUN_NUM: ${{ env.GITHUB_RUN_NUMBER }}

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build benchmark docker image
        run: docker build . --file ./benches/Dockerfile --tag benchmark:$RUN_NUM

      - name: Run benchmark
        run: docker run --privileged --rm -it benchmark:$RUN_NUM


